### ISSUE TITLE
Can it highlight the code ?

### ISSUE THREAD

**Issue by xiekeyi98** [fletchto99/hexo-sliding-spoiler#3]
I test it , and can not highlight the code .

My code is as fellow 
```

{% spoiler title %}
```c++
my code
```
{% endspoiler %}

```

**Comment by fletchto99** [comment]
Code within spoilers is actually handled via code blocks, for example:


```
{% codeblock lang:c++ filename.cpp %}
//Code here
{% endcodeblock %}
```

See https://hexo.io/docs/tag-plugins.html#Code-Block for more information on the codeblock tag.
