### ISSUE TITLE
putting a code block inside a spoiler display undefined

### ISSUE THREAD

**Issue by noraj** [fletchto99/hexo-sliding-spoiler#5]
Putting a very long fanced code block bewteen spoiler tags I get `undefined` instead of the code.

~~~
{% spoiler title %}
sometext:

```python
0 :  <class 'type'>
1 :  <class 'weakref'>
[...]
157:
```
{% endspoiler %}
~~~

All is rendered except the code. I suspect this is because of the `<>` surrounding the classes.

Outside the spoiler tags this is rendered properly (I'm using hexo-renderer-markdown-it).

https://github.com/fletchto99/hexo-sliding-spoiler/blob/7b4aeb3ea7dbf30e3ac7e72292ae756fd4b3eeef/index.js#L4-L7

**Comment by noraj** [comment]
In fact I also added a normal code block

~~~
```
test
```
~~~

and it also results into undefined

**Comment by fletchto99** [comment]
I'll have to look into this. In the meantime I suggest taking a look into using [code blocks](https://hexo.io/docs/tag-plugins.html#Code-Block). See #3 - I believe that was the same issue.

**Comment by noraj** [comment]
~~~erb
{% spoiler subclasses %}
{% codeblock lang:python %}
code here
{% endcodeblock %}
{% endspoiler %}
~~~

Worked but this require less markdown and more template lang. Also loosing the syntax highlight in the code editor.

**Comment by fletchto99** [comment]
I'm looking into this over the christmas break. I'm hoping to have a fix by the end of the week.

**Comment by fletchto99** [comment]
The latest version `1.2.0` has been published to NPM fixing this issue. The fix was easier than I expected :) - Sorry it took so long to get to, this project hasn't been a high priority recently 😓
