### ISSUE TITLE
assets are not generated when the blog is in sub-directory

### ISSUE THREAD

**Issue by Shedarshian** [fletchto99/hexo-sliding-spoiler#8]
The 'after_post_render' filter seems to use only /js/spoiler.js and /css/spoiler.css from the root directory. When I publish the page into a sub-directory of git-pages, it does not work.

**Comment by fletchto99** [comment]
Hey @Shedarshian is this still an issue for you. What do you have in you're blogs `_config.yml` for the `root`?

For example, from their docs: If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'.

**Comment by Shedarshian** [comment]
The root in my _config.yml is correct:

```xaml
url: https://shedarshian.github.io/blog
root: /blog/
```

Currently I change the source code
  https://github.com/fletchto99/hexo-sliding-spoiler/blob/166a65e79404caf4e52770e74b22211327d26569/index.js#L36-L41
to:

```javascript
hexo.extend.filter.register('after_post_render', (data) => {
    var link_css = "<link rel=\"stylesheet\" href=\"/blog/css/spoiler.css\" type=\"text/css\">";
    var link_js = "<script src=\"/blog/js/spoiler.js\" type=\"text/javascript\" async></script>";
    data.content += link_css + link_js;
    return data;
});
```

**Comment by fletchto99** [comment]
Can you let me know if `v1.2.1` fixes this? https://www.npmjs.com/package/hexo-sliding-spoiler - I now set the path relative using the provided root in the config.

**Comment by Shedarshian** [comment]
Ah, ok, it works!
Thanks for repairing the bug
